"""
code_generator.py - Code Generator
====================================
Walks the language-agnostic IR tree and emits target-language
source code, preserving the original architecture while applying
idiomatic patterns for the target language.

Supported targets: Rust, Go, Java, TypeScript
"""

from __future__ import annotations
from typing import Optional
from ast_generator import IRNode, IRType, NodeKind
from language_mapping_engine import LanguageMappingEngine

INDENT = "    "


# ---------------------------------------------------------------------------
# Base generator
# ---------------------------------------------------------------------------
class BaseCodeGenerator:
    """Abstract base: subclass for each target language."""

    def __init__(self, engine: LanguageMappingEngine):
        self.engine = engine
        self._lines: list[str] = []
        self._indent_level = 0

    # -- helpers -----------------------------------------------------------
    def emit(self, line: str = "") -> None:
        prefix = INDENT * self._indent_level
        self._lines.append(prefix + line)

    def indent(self):  return _IndentCtx(self)
    def blank(self):   self._lines.append("")
    def render(self) -> str: return "
".join(self._lines)

    # -- entry point -------------------------------------------------------
    def generate(self, ir: IRNode) -> str:
        self._lines.clear()
        self._indent_level = 0
        self._emit_header()
        for child in ir.children:
            self._visit(child)
        return self.render()

    def _emit_header(self): pass
    def _visit(self, node: IRNode) -> None:
        dispatch = {
            NodeKind.IMPORT:   self._visit_import,
            NodeKind.CLASS:    self._visit_class,
            NodeKind.FUNCTION: self._visit_function,
            NodeKind.METHOD:   self._visit_function,
            NodeKind.ASSIGN:   self._visit_assign,
            NodeKind.RETURN:   self._visit_return,
            NodeKind.IF:       self._visit_if,
            NodeKind.FOR:      self._visit_for,
            NodeKind.WHILE:    self._visit_while,
            NodeKind.TRY_CATCH:self._visit_try,
        }
        fn = dispatch.get(node.kind, self._visit_unknown)
        fn(node)
        for child in node.children:
            self._visit(child)

    def _visit_import(self, n): pass
    def _visit_class(self, n):  pass
    def _visit_function(self, n): pass
    def _visit_assign(self, n): pass
    def _visit_return(self, n): pass
    def _visit_if(self, n):     pass
    def _visit_for(self, n):    pass
    def _visit_while(self, n):  pass
    def _visit_try(self, n):    pass
    def _visit_unknown(self, n):
        self.emit(f"// [untranslated: {n.kind.value} '{n.name or ''}']")


class _IndentCtx:
    def __init__(self, gen):  self._gen = gen
    def __enter__(self):      self._gen._indent_level += 1; return self
    def __exit__(self, *_):   self._gen._indent_level -= 1


# ---------------------------------------------------------------------------
# Rust generator
# ---------------------------------------------------------------------------
class RustCodeGenerator(BaseCodeGenerator):

    def _emit_header(self):
        self.emit("// Auto-generated by AI Codebase Translator")
        self.emit("// Source language: " + self.engine.source_lang)
        self.emit("#![allow(unused_imports, dead_code, unused_variables)]")
        self.blank()
        self.emit("use std::collections::HashMap;")
        self.emit("use std::collections::HashSet;")
        self.blank()

    def _visit_import(self, n: IRNode):
        if isinstance(n.value, list):
            for imp in n.value:
                mapped = self.engine.map_stdlib(imp)
                self.emit(f"// import: {imp}  =>  use {mapped};")

    def _visit_class(self, n: IRNode):
        self.blank()
        if n.docstring:
            for line in n.docstring.splitlines():
                self.emit(f"/// {line}")
        # Fields
        fields = [c for c in n.children if c.kind == NodeKind.FIELD]
        self.emit(f"pub struct {n.name} {{")
        with self.indent():
            if fields:
                for f in fields:
                    ft = self.engine.map_type(f.ir_type) or "String"
                    self.emit(f"pub {_snake(f.name)}: {ft},")
            else:
                self.emit("// fields translated from source")
        self.emit("}")
        self.blank()
        # impl block for methods
        methods = [c for c in n.children if c.kind in (NodeKind.FUNCTION, NodeKind.METHOD)]
        if methods:
            self.emit(f"impl {n.name} {{")
            with self.indent():
                for m in methods:
                    self._emit_rust_fn(m, is_method=True)
            self.emit("}")

    def _emit_rust_fn(self, n: IRNode, is_method=False):
        self.blank()
        if n.docstring:
            self.emit(f"/// {n.docstring.splitlines()[0]}")
        params = [c for c in n.children if c.kind == NodeKind.PARAMETER]
        param_strs = []
        for p in params:
            if p.name == "self":
                param_strs.append("&self")
            else:
                pt = self.engine.map_type(p.ir_type) or "String"
                param_strs.append(f"{_snake(p.name)}: {pt}")
        ret = self.engine.map_type(n.ir_type)
        ret_str = f" -> {ret}" if ret and ret != "()" else ""
        param_sig = ", ".join(param_strs)
        self.emit(f"pub fn {_snake(n.name)}({param_sig}){ret_str} {{")
        with self.indent():
            self.emit("// TODO: implement translated body")
            if ret and ret != "()":
                self.emit(f"unimplemented!()")
        self.emit("}")

    def _visit_function(self, n: IRNode):
        # Only emit top-level functions (not inside a class handled above)
        self._emit_rust_fn(n)

    def _visit_return(self, n: IRNode):
        val = n.value or "()"
        self.emit(f"return {val};")

    def _visit_if(self, n: IRNode):
        cond = n.metadata.get("test", "condition")
        self.emit(f"if {cond} {{")
        with self.indent():
            self.emit("// translated if body")
        self.emit("}")

    def _visit_for(self, n: IRNode):
        tgt = n.metadata.get("target", "item")
        it  = n.metadata.get("iter", "items")
        self.emit(f"for {_snake(tgt)} in {_snake(it)}.iter() {{")
        with self.indent():
            self.emit("// translated loop body")
        self.emit("}")

    def _visit_while(self, n: IRNode):
        cond = n.metadata.get("test", "true")
        self.emit(f"while {cond} {{")
        with self.indent():
            self.emit("// translated while body")
        self.emit("}")

    def _visit_try(self, n: IRNode):
        self.emit("// try/catch -> Rust Result pattern")
        self.emit("let result = (|| -> Result<_, Box<dyn std::error::Error>> {")
        with self.indent():
            self.emit("// translated try body")
            self.emit("Ok(())")
        self.emit("})();")
        self.emit("match result {")
        with self.indent():
            self.emit("Ok(v) => { /* success */ }")
            self.emit("Err(e) => { eprintln!("Error: {}", e); }")
        self.emit("}")


# ---------------------------------------------------------------------------
# Go generator
# ---------------------------------------------------------------------------
class GoCodeGenerator(BaseCodeGenerator):

    def _emit_header(self):
        self.emit("// Auto-generated by AI Codebase Translator")
        self.emit(f"// Source language: {self.engine.source_lang}")
        self.blank()
        self.emit("package main")
        self.blank()
        self.emit("import (")
        with self.indent():
            self.emit('"fmt"')
            self.emit('"errors"')
        self.emit(")")
        self.blank()

    def _visit_import(self, n: IRNode):
        if isinstance(n.value, list):
            for imp in n.value:
                mapped = self.engine.map_stdlib(imp)
                self.emit(f"// import {imp} -> {mapped}")

    def _visit_class(self, n: IRNode):
        self.blank()
        if n.docstring:
            self.emit(f"// {n.docstring.splitlines()[0]}")
        fields = [c for c in n.children if c.kind == NodeKind.FIELD]
        self.emit(f"type {n.name} struct {{")
        with self.indent():
            if fields:
                for f in fields:
                    ft = self.engine.map_type(f.ir_type) or "string"
                    self.emit(f"{_pascal(f.name)} {ft}")
            else:
                self.emit("// fields from source")
        self.emit("}")
        self.blank()
        # Constructor
        self.emit(f"func New{n.name}() *{n.name} {{")
        with self.indent():
            self.emit(f"return &{n.name}{{}}")
        self.emit("}")
        # Methods
        for m in [c for c in n.children if c.kind in (NodeKind.FUNCTION, NodeKind.METHOD)]:
            self._emit_go_method(m, receiver=n.name)

    def _emit_go_method(self, n: IRNode, receiver: str = ""):
        self.blank()
        params = [c for c in n.children if c.kind == NodeKind.PARAMETER and c.name != "self"]
        param_strs = [f"{_camel(p.name)} {self.engine.map_type(p.ir_type) or 'string'}" for p in params]
        ret = self.engine.map_type(n.ir_type) or ""
        ret_str = f" {ret}" if ret else ""
        recv = f"(r *{receiver}) " if receiver else ""
        self.emit(f"func {recv}{_pascal(n.name)}({', '.join(param_strs)}){ret_str} {{")
        with self.indent():
            self.emit("// TODO: implement translated body")
        self.emit("}")

    def _visit_function(self, n: IRNode):
        self._emit_go_method(n)

    def _visit_return(self, n: IRNode):
        val = n.value or ""
        self.emit(f"return {val}")

    def _visit_if(self, n: IRNode):
        cond = n.metadata.get("test", "condition")
        self.emit(f"if {cond} {{")
        with self.indent():
            self.emit("// translated if body")
        self.emit("}")

    def _visit_for(self, n: IRNode):
        tgt = _camel(n.metadata.get("target", "item"))
        it  = _camel(n.metadata.get("iter", "items"))
        self.emit(f"for _, {tgt} := range {it} {{")
        with self.indent():
            self.emit("// translated loop body")
        self.emit("}")

    def _visit_while(self, n: IRNode):
        cond = n.metadata.get("test", "true")
        self.emit(f"for {cond} {{")
        with self.indent():
            self.emit("// translated while body")
        self.emit("}")

    def _visit_try(self, n: IRNode):
        self.emit("// Python try/except -> Go error return pattern")
        self.emit("if err := riskyOperation(); err != nil {")
        with self.indent():
            self.emit('fmt.Printf("Error: %v\n", err)')
        self.emit("}")


# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------
def _snake(name: str) -> str:
    """Convert camelCase / PascalCase to snake_case."""
    import re
    if not name:
        return "unknown"
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def _pascal(name: str) -> str:
    """Convert snake_case to PascalCase."""
    if not name:
        return "Unknown"
    return "".join(word.capitalize() for word in name.split("_"))


def _camel(name: str) -> str:
    """Convert snake_case to camelCase."""
    pascal = _pascal(name)
    return pascal[0].lower() + pascal[1:] if pascal else name


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
GENERATORS = {
    "rust": RustCodeGenerator,
    "go":   GoCodeGenerator,
}


def generate_code(ir: IRNode, source_lang: str, target_lang: str) -> str:
    """
    Generate target-language source code from an IR tree.
    Returns the translated source as a string.
    """
    from language_mapping_engine import create_mapping_engine
    engine = create_mapping_engine(source_lang, target_lang)
    gen_cls = GENERATORS.get(target_lang)
    if not gen_cls:
        return f"// Code generation for '{target_lang}' not yet implemented\n"
    return gen_cls(engine).generate(ir)
